service: budgetly-api
useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: ap-south-1
  apiGateway:
    binaryMediaTypes:
      - "*/*"
  environment:
    ALLOWED_ORIGINS_PROD: ${env:ALLOWED_ORIGINS_PROD}
    ALLOWED_ORIGINS_LOCAL: ${env:ALLOWED_ORIGINS_LOCAL}
    MONGODB_URI: ${env:MONGODB_URI}
    DB_NAME: ${env:DB_NAME}
    ACCESS_TOKEN_SECRET: ${env:ACCESS_TOKEN_SECRET}
    ACCESS_TOKEN_EXPIRY: ${env:ACCESS_TOKEN_EXPIRY}
    REFRESH_TOKEN_SECRET: ${env:REFRESH_TOKEN_SECRET}
    REFRESH_TOKEN_EXPIRY: ${env:REFRESH_TOKEN_EXPIRY}
    CLOUDINARY_CLOUD_NAME: ${env:CLOUDINARY_CLOUD_NAME}
    CLOUDINARY_API_KEY: ${env:CLOUDINARY_API_KEY}
    CLOUDINARY_SECRET_KEY: ${env:CLOUDINARY_SECRET_KEY}

functions:
  api:
    handler: src/index.handler
    events:
      - http:
          path: /{proxy+}
          method: ANY
          cors:
            origin: "https://budgetly-two.vercel.app" # Note the single quotes inside double quotes
            headers:
              - Content-Type
              - Authorization
              - X-Amz-Date
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Requested-With
            allowCredentials: true
            maxAge: 86400

plugins:
  - serverless-offline
  - serverless-dotenv-plugin

custom:
  dotenv:
    path: .env
